/**
 * Candlestick patterns registry — 55+ patterns with entry/exit logic.
 */
import type { CandlestickPatternDef, MarketRegime, TradeStyle } from '../types';

const S: TradeStyle[] = ['scalping', 'day', 'medium_swing', 'swing', 'sniper'];

function cs(
  id: string,
  name: string,
  logic: string,
  regimes: MarketRegime[],
  styles: TradeStyle[],
  entryLogic: string,
  exitLogic: string,
  enabled = true
): CandlestickPatternDef {
  return { id, name, category: 'candlestick', logic, regimes, styles, enabled, entryLogic, exitLogic };
}

export const CANDLESTICK_PATTERNS: CandlestickPatternDef[] = [
  cs('cs-engulfing-bull', 'Bullish Engulfing', 'Down trend; green body fully engulfs prior red.', ['reversal_bull', 'trending_bear', 'ranging'], S, 'Entry on close above prior high; volume.', 'Target prior swing high or 1:1.5 R:R; stop below engulfing low.'),
  cs('cs-engulfing-bear', 'Bearish Engulfing', 'Up trend; red body fully engulfs prior green.', ['reversal_bear', 'trending_bull', 'ranging'], S, 'Entry on close below prior low.', 'Target prior swing low; stop above engulfing high.'),
  cs('cs-hammer', 'Hammer', 'Small body at top, long lower wick; rejection of lows.', ['reversal_bull', 'ranging'], S, 'Entry on next candle confirmation at support.', 'Target resistance or 1:2 R:R; stop below hammer low.'),
  cs('cs-inverted-hammer', 'Inverted Hammer', 'Long upper wick, small body at bottom; potential bullish reversal.', ['reversal_bull', 'trending_bear'], S, 'Entry on close above hammer high.', 'Target prior resistance; stop below low.'),
  cs('cs-hanging-man', 'Hanging Man', 'Hammer shape after uptrend; bearish reversal.', ['reversal_bear', 'trending_bull'], S, 'Entry on break below body with volume.', 'Target prior support; stop above high.'),
  cs('cs-shooting-star', 'Shooting Star', 'Long upper wick, small body at bottom after uptrend.', ['reversal_bear', 'trending_bull'], S, 'Entry on break below body.', 'Target prior support.'),
  cs('cs-morning-star', 'Morning Star (3-candle)', 'Long red, small star, long green; bullish reversal.', ['reversal_bull', 'trending_bear'], ['day', 'medium_swing', 'swing', 'sniper'], 'Entry on close of third above midpoint of first.', 'Target first candle range projected up.'),
  cs('cs-evening-star', 'Evening Star (3-candle)', 'Long green, small star, long red; bearish reversal.', ['reversal_bear', 'trending_bull'], ['day', 'medium_swing', 'swing', 'sniper'], 'Entry on close of third below midpoint.', 'Target first candle range down.'),
  cs('cs-doji', 'Doji (Indecision)', 'Open ≈ close; small body at key level.', ['ranging', 'reversal_bull', 'reversal_bear', 'consolidation'], ['scalping', 'day', 'sniper'], 'Entry with level confluence; next-candle confirmation.', 'Target next structure; stop beyond doji.'),
  cs('cs-dragonfly-doji', 'Dragonfly Doji', 'Doji with long lower wick; bullish at support.', ['reversal_bull', 'ranging'], S, 'Entry on break above open/high.', 'Target resistance; stop below wick.'),
  cs('cs-gravestone-doji', 'Gravestone Doji', 'Doji with long upper wick; bearish at resistance.', ['reversal_bear', 'ranging'], S, 'Entry on break below open/low.', 'Target support.'),
  cs('cs-pin-bar-bull', 'Bullish Pin Bar', 'Long lower wick, small body; rejection of support.', ['reversal_bull', 'ranging', 'breakout'], S, 'Entry on break of body high.', 'Target 1:1.5 or structure; stop beyond wick.'),
  cs('cs-pin-bar-bear', 'Bearish Pin Bar', 'Long upper wick; rejection of resistance.', ['reversal_bear', 'ranging', 'breakout'], S, 'Entry on break of body low.', 'Target 1:1.5; stop beyond wick.'),
  cs('cs-three-soldiers', 'Three White Soldiers', 'Three consecutive green candles, higher closes.', ['trending_bull', 'breakout', 'reversal_bull'], ['day', 'medium_swing', 'swing'], 'Entry on pullback to first/second body.', 'Target prior resistance or ATR; stop below third.'),
  cs('cs-three-crows', 'Three Black Crows', 'Three consecutive red candles, lower closes.', ['trending_bear', 'breakout', 'reversal_bear'], ['day', 'medium_swing', 'swing'], 'Entry on pullback to first/second body.', 'Target prior support; stop above third.'),
  cs('cs-three-white-crows', 'Three White Crows', 'Variant; each opens within prior body.', ['trending_bull', 'breakout'], ['day', 'swing'], 'Entry on pullback.', 'Target measured move.'),
  cs('cs-advance-block', 'Advance Block', 'Three green candles with shrinking bodies; weakening bullish.', ['reversal_bear', 'trending_bull'], ['day', 'swing'], 'Entry on break below third candle.', 'Target prior support.'),
  cs('cs-deliberation', 'Deliberation', 'Two long green then small body; pause before reversal.', ['reversal_bear', 'trending_bull'], ['day', 'swing'], 'Entry on bearish confirmation.', 'Target prior low.'),
  cs('cs-two-crows', 'Two Crows', 'Long green, gap up, two small red; bearish.', ['reversal_bear'], ['day', 'swing'], 'Entry on break below first green open.', 'Target prior support.'),
  cs('cs-three-inside', 'Three Inside Up', 'Down trend; engulfing then higher close.', ['reversal_bull', 'trending_bear'], ['day', 'swing', 'sniper'], 'Entry on close above second candle high.', 'Target prior resistance.'),
  cs('cs-three-outside', 'Three Outside Up', 'Engulfing then higher close; strong bullish.', ['reversal_bull', 'breakout'], ['day', 'swing'], 'Entry on break above third.', 'Target measured move.'),
  cs('cs-abandoned-baby-bull', 'Abandoned Baby (Bull)', 'Gap down, doji, gap up; rare bullish reversal.', ['reversal_bull', 'trending_bear'], ['day', 'swing'], 'Entry on break above doji.', 'Target prior high.'),
  cs('cs-abandoned-baby-bear', 'Abandoned Baby (Bear)', 'Gap up, doji, gap down; bearish reversal.', ['reversal_bear', 'trending_bull'], ['day', 'swing'], 'Entry on break below doji.', 'Target prior low.'),
  cs('cs-kicking-bull', 'Kicking (Bull)', 'Marubozu down then gap up marubozu; bullish.', ['reversal_bull', 'breakout'], ['day', 'scalping'], 'Entry on open of second.', 'Target prior resistance.'),
  cs('cs-kicking-bear', 'Kicking (Bear)', 'Marubozu up then gap down marubozu; bearish.', ['reversal_bear', 'breakout'], ['day', 'scalping'], 'Entry on open of second.', 'Target prior support.'),
  cs('cs-ladder-bottom', 'Ladder Bottom', 'Five candles; down then strong up close; bullish.', ['reversal_bull'], ['day', 'swing'], 'Entry on break above fifth high.', 'Target prior resistance.'),
  cs('cs-mat-hold', 'Mat Hold', 'Gap up, three small down, strong green; bullish continuation.', ['trending_bull', 'breakout'], ['day', 'swing'], 'Entry on break above first candle.', 'Target prior high.'),
  cs('cs-rising-three', 'Rising Three Methods', 'Long green, three small down inside range, green; bullish.', ['trending_bull'], ['day', 'swing'], 'Entry on break above first green.', 'Target prior high.'),
  cs('cs-falling-three', 'Falling Three Methods', 'Long red, three small up, red; bearish.', ['trending_bear'], ['day', 'swing'], 'Entry on break below first red.', 'Target prior low.'),
  cs('cs-tasuki-gap-up', 'Upside Tasuki Gap', 'Gap up, green, red opening in gap; bullish continuation.', ['trending_bull'], ['day', 'scalping'], 'Entry on break above first green.', 'Target prior high.'),
  cs('cs-tasuki-gap-down', 'Downside Tasuki Gap', 'Gap down, red, green opening in gap; bearish continuation.', ['trending_bear'], ['day', 'scalping'], 'Entry on break below first red.', 'Target prior low.'),
  cs('cs-on-neck', 'On-Neck Line', 'Long red, small green closing at prior low; bearish continuation.', ['trending_bear'], ['day'], 'Entry on break below.', 'Target prior support.'),
  cs('cs-in-neck', 'In-Neck Line', 'Similar; green closes slightly into red body.', ['trending_bear'], ['day'], 'Entry on break below.', 'Target prior low.'),
  cs('cs-thrusting', 'Thrusting Line', 'Red then green closing into red body but below midpoint.', ['trending_bear'], ['day'], 'Weak bullish; short on break below.', 'Target prior low.'),
  cs('cs-stick-sandwich', 'Stick Sandwich', 'Red, green, red; green between two red; bullish reversal.', ['reversal_bull', 'trending_bear'], ['day', 'swing'], 'Entry on break above first red high.', 'Target prior resistance.'),
  cs('cs-three-stars-south', 'Three Stars in South', 'Three declining dojis; rare bearish.', ['reversal_bear'], ['day', 'swing'], 'Entry on break below.', 'Target prior support.'),
  cs('cs-tri-star', 'Tri-Star', 'Three dojis with gaps; major reversal.', ['reversal_bull', 'reversal_bear'], ['swing'], 'Entry on break of middle doji.', 'Target prior swing.'),
  cs('cs-identical-three-crows', 'Identical Three Crows', 'Three red with same open; strong bearish.', ['reversal_bear', 'trending_bull'], ['day', 'swing'], 'Entry on break below.', 'Target prior support.'),
  cs('cs-morning-doji-star', 'Morning Doji Star', 'Long red, doji gap down, long green; bullish.', ['reversal_bull', 'trending_bear'], ['day', 'swing', 'sniper'], 'Entry on close above first body.', 'Target first candle range up.'),
  cs('cs-evening-doji-star', 'Evening Doji Star', 'Long green, doji gap up, long red; bearish.', ['reversal_bear', 'trending_bull'], ['day', 'swing', 'sniper'], 'Entry on close below first body.', 'Target first candle range down.'),
  cs('cs-harami-bull', 'Bullish Harami', 'Long red then small green inside red body; reversal.', ['reversal_bull', 'trending_bear'], S, 'Entry on break above red high.', 'Target prior resistance; stop below red low.'),
  cs('cs-harami-bear', 'Bearish Harami', 'Long green then small red inside green body.', ['reversal_bear', 'trending_bull'], S, 'Entry on break below green low.', 'Target prior support.'),
  cs('cs-harami-cross-bull', 'Harami Cross (Bull)', 'Long red then doji inside; bullish reversal.', ['reversal_bull'], S, 'Entry on break above.', 'Target prior high.'),
  cs('cs-harami-cross-bear', 'Harami Cross (Bear)', 'Long green then doji inside; bearish.', ['reversal_bear'], S, 'Entry on break below.', 'Target prior low.'),
  cs('cs-piercing', 'Piercing Line', 'Long red, green opens below and closes above midpoint of red.', ['reversal_bull', 'trending_bear'], S, 'Entry on break above green high.', 'Target prior resistance.'),
  cs('cs-dark-cloud', 'Dark Cloud Cover', 'Long green, red opens above and closes below midpoint.', ['reversal_bear', 'trending_bull'], S, 'Entry on break below red low.', 'Target prior support.'),
  cs('cs-tweezer-top', 'Tweezer Tops', 'Two candles with same high; bearish.', ['reversal_bear', 'ranging'], S, 'Entry on break below.', 'Target next support.'),
  cs('cs-tweezer-bottom', 'Tweezer Bottoms', 'Two candles with same low; bullish.', ['reversal_bull', 'ranging'], S, 'Entry on break above.', 'Target next resistance.'),
  cs('cs-marubozu-white', 'White Marubozu', 'Long green, no wicks; strong bullish.', ['trending_bull', 'breakout', 'reversal_bull'], S, 'Entry on pullback or next candle.', 'Target prior resistance or ATR.'),
  cs('cs-marubozu-black', 'Black Marubozu', 'Long red, no wicks; strong bearish.', ['trending_bear', 'breakout', 'reversal_bear'], S, 'Entry on pullback or next candle.', 'Target prior support.'),
  cs('cs-spinning-top-bull', 'Spinning Top (Bull Context)', 'Small body, long wicks at support; indecision then up.', ['reversal_bull', 'ranging'], ['scalping', 'day', 'sniper'], 'Entry on break above with volume.', 'Target resistance.'),
  cs('cs-spinning-top-bear', 'Spinning Top (Bear Context)', 'Small body at resistance; indecision then down.', ['reversal_bear', 'ranging'], ['scalping', 'day', 'sniper'], 'Entry on break below.', 'Target support.'),
  cs('cs-high-wave', 'High Wave Candle', 'Long upper and lower wicks; indecision.', ['ranging', 'reversal_bull', 'reversal_bear'], ['scalping', 'day'], 'Entry with level confluence; confirm next.', 'Target structure.'),
  cs('cs-belt-hold-bull', 'Belt Hold (Bull)', 'Long green opening at low; strong bullish.', ['reversal_bull', 'breakout'], ['day', 'scalping'], 'Entry on break above high.', 'Target prior resistance.'),
  cs('cs-belt-hold-bear', 'Belt Hold (Bear)', 'Long red opening at high; strong bearish.', ['reversal_bear', 'breakout'], ['day', 'scalping'], 'Entry on break below low.', 'Target prior support.'),
  cs('cs-breakaway-bull', 'Breakaway (Bull)', 'Down trend; gap down, three up, gap up; bullish.', ['reversal_bull'], ['day', 'swing'], 'Entry on break above.', 'Target prior high.'),
  cs('cs-breakaway-bear', 'Breakaway (Bear)', 'Up trend; gap up, three down, gap down; bearish.', ['reversal_bear'], ['day', 'swing'], 'Entry on break below.', 'Target prior low.'),
  cs('cs-concealing-baby', 'Concealing Baby Swallow', 'Four black candles; fourth opens within third; bullish reversal.', ['reversal_bull'], ['day', 'swing'], 'Entry on break above first high.', 'Target prior resistance.'),
  cs('cs-unique-three-river', 'Unique Three River Bottom', 'Long red, hammer, small green inside hammer; bullish.', ['reversal_bull', 'trending_bear'], ['day', 'swing'], 'Entry on break above first red high.', 'Target prior resistance.'),
  cs('cs-two-rabbits', 'Two Rabbits', 'Gap down, two green; second opens in first body; bullish.', ['reversal_bull'], ['day'], 'Entry on break above.', 'Target prior high.'),
  cs('cs-three-line-strike-bull', 'Three Line Strike (Bull)', 'Three red then green engulfing; bullish reversal.', ['reversal_bull', 'trending_bear'], ['day', 'swing'], 'Entry on break above green.', 'Target prior resistance.'),
  cs('cs-three-line-strike-bear', 'Three Line Strike (Bear)', 'Three green then red engulfing; bearish.', ['reversal_bear', 'trending_bull'], ['day', 'swing'], 'Entry on break below red.', 'Target prior support.'),
  cs('cs-three-river-bull', 'Three River Bottom', 'Long red, doji at low, small green; bullish.', ['reversal_bull'], ['day', 'swing'], 'Entry on break above first red high.', 'Target prior high.'),
  cs('cs-northern-doji', 'Northern Doji', 'Doji after uptrend; potential top.', ['reversal_bear', 'trending_bull'], ['day', 'sniper'], 'Entry on break below.', 'Target prior support.'),
  cs('cs-southern-doji', 'Southern Doji', 'Doji after downtrend; potential bottom.', ['reversal_bull', 'trending_bear'], ['day', 'sniper'], 'Entry on break above.', 'Target prior resistance.'),
];
